import os.path

finnhub_base_url = "https://finnhub.io"
default_api_rate_limit = 60
destination_file = os.path.join(os.path.dirname(os.path.dirname(__file__)), "most_volatile_stock.csv")

# Raw got from https://finnhub.io/api/v1/search?q={} but filtered and checked manually
stock_symbols = [
    # Apple: Search by q=APPL
    "AAPL",
    "AAPL.SN",
    "AAPL.MX",
    "AAPL.AS",
    "AAPL.MI",
    "AAPL.SW",
    "AAPL.L",
    "AAPL.NE",
    "AAPL.VI",
    "AAPL.TWO",
    "AAPL.BC",
    # Amazon: Search by q=AMZN
    "AMZN",
    "AMZN.BC",
    "AMZN.SW",
    "AMZN.NE",
    "AMZN.MX",
    "AMZN.AS",
    "AMZN.TWO",
    "AMZN.MI",
    "AMZN.SN",
    "AMZN.VI",
    "AMZN.L",
    # Netflix search by q=NFLX
    "NFLX",
    "NFLX.VI",
    "NFLX.MI",
    "NFLX.L",
    "NFLX.AS",
    "NFLX.NE",
    "NFLX.SW",
    "NFLX.MX",
    "NFLX.TWO",
    # Facebook search by q=META PLATFORMS
    "META",
    "FB20.F",
    "MVRS.TWO",
    "FB20.BE",
    "FB20.MU",
    "MVRS.NE",
    "FB.VI",
    "FB2A.DE",
    "0QZI.L",
    "FB2A.HM",
    "FBCL.SN",
    "FB2A.F",
    "FBUSD.SW",
    "FB.SW",
    "FB.SN",
    "FB-RM.ME",
    "MVRS.MI",
    "FB2A.SG",
    "FB2A.DU",
    "FB2A.HA",
    "FB2A.BE",
    "META.MX",
    # Google: search by q=GOOG
    "GOOGL",
    "GOOG.L",
    "GOOG.MI",
    "GOOGL1.BA",
    "GOOGL.MX",
    "ABEA.SG",
    "GOOGL.SW",
    "GOOGL.SN",
    "GOOA.VI",
    "GOOGL.MI",
    "0HD6.L",
    "0RIH.L",
    "ABEA.HM",
    "GOOGCL.SN",
    "GOOG.NE",
    "ABEA.DE",
    "ABEC.MU",
    "ABEA.MU",
    "ABEC.F",
    "GOOGL2.BA",
    "GOOGLCL.SN",
    "ABEC.DU",
    "GOOG.AS",
    "GOOGLD2.BA",
    "GOOG.MX",
    "GOGL35.SA",
    "ABEA.F",
    "GOOG",
    "GOOC.VI",
    "ABEA.BE",
    "ABEC.DE",
    "GOOGLD1.BA",
    "GOOG-RM.ME",
    "GOOGLD3.BA",
    "GOGL35F.SA",
    "GOGL34.SA",
    "GOGL34F.SA",
    "GOOG.SN",
    "GOOGLC3.BA",
    "ABEC.BE",
    "GOOGL3.BA",
    "ABEA.DU",
    "ABEC.SG",
    "ABEC.HM"
]
